# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  ImageUploader:
    class: AppBundle\Services\ImageUploader
    arguments: [ @kernel ]
    # arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  AlbumService:
    class: AppBundle\Services\AlbumService
    arguments: [ @ImageUploader, @doctrine ]


  app.twig_extension:
    class: AppBundle\Twig\PrefetchExtension
    public: false
    arguments: [ @serializer ]
    tags:
      - { name: twig.extension }